"""Added new fields to Book model

Revision ID: 29ea2c9491d9
Revises: 1f5d8b087922
Create Date: 2025-02-14 18:57:56.242853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ea2c9491d9'
down_revision = '1f5d8b087922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publishlocation')
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('isbn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('issn', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('journal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('collection', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('person_liable', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('organization_liable', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['issn'])
        batch_op.create_unique_constraint(None, ['isbn'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('organization_liable')
        batch_op.drop_column('person_liable')
        batch_op.drop_column('collection')
        batch_op.drop_column('journal')
        batch_op.drop_column('issn')
        batch_op.drop_column('isbn')
        batch_op.drop_column('language')

    op.create_table('publishlocation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('book_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
